### ISSUE TITLE
'require-dir' in both dependencies and dev-dependencies

### ISSUE THREAD

**Issue by thierrydelbart** [therebelrobot/brigadehub#208]
#### Description

I'm running Node 4.4.3 (now) and I receive the following warning on `npm install`:

```
npm WARN package.json Dependency 'require-dir' exists in both dependencies and devDependencies, using 'require-dir@^0.3.0' from dependencies
```

Is there a problem with the current package.json ?

**Comment by johngluck65** [comment]
@therebelrobot should I remove this from dependencies or devDependencies or do you not know and that's why it's not gone?

**Comment by johngluck65** [comment]
So I figured out that app.js uses this, so I removed it from devDependencies.

**Comment by johngluck65** [comment]
Should be settled now @Thithi32
