### ISSUE TITLE
Responsive stats on landing page

### ISSUE THREAD

**Issue by thierrydelbart** [therebelrobot/brigadehub#245]
#### Description

Make landing page stats section responsive

**Comment by toddseller** [comment]
## Description

Make landing page responsive for mobile.
- Enhance Upcoming Events section to mirror Code for Poland's styling and make responsive.
- Center rows within the body of the landing page.
- Center Partner logos.
- Adjust styling of Projects to be more responsive.
- Hide statistics in mobile.
