### ISSUE TITLE
Events on front page not linked to the Events page

### ISSUE THREAD

**Issue by davidcarvel** [therebelrobot/brigadehub#258]
#### Description

There are events listed in the "Upcoming Events" banner on the homepage. They do not link to the Events calendar. The events do not show up on the calendar when you go to January (the month the events are listed -- though perhaps that is because the events are dated for a year other than 2016).
#### To Reproduce

Try to click on an event from the homepage. 
#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Remember to use helpful labels and milestones. If you use the "help wanted" label, Code for America will [promote it widely](http://www.codeforamerica.org/geeks/civicissues).

**Comment by Juxtaposeidon** [comment]
should be fixed with  #213. the calendar on that PR syncs with upcoming events instead of having static placeholders.

**Comment by Juxtaposeidon** [comment]
closed because fixed ^^
