### ISSUE TITLE
Email addresses in Contacts are Undefined

### ISSUE THREAD

**Issue by davidcarvel** [therebelrobot/brigadehub#263]
#### Description

Some of the email addresses in the Contacts page are undefined (likely due to not being entered in GitHub profile). Is this our desired default behavior? 
#### Screenshots

![image](https://cloud.githubusercontent.com/assets/17933351/15126289/5371be0c-15ff-11e6-8caa-51f0777670fd.png)
#### Files

A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
#### To Reproduce

Go to Home > Contacts. Hover/click on an email address for Trent, Jesse B, or David
#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Remember to use helpful labels and milestones. If you use the "help wanted" label, Code for America will [promote it widely](http://www.codeforamerica.org/geeks/civicissues).

**Comment by Juxtaposeidon** [comment]
fixed #271
