### ISSUE TITLE
After Publishing Blog post, Blog screen shows "draft"

### ISSUE THREAD

**Issue by davidcarvel** [therebelrobot/brigadehub#265]
#### Description

I published a blog post but the Blog page shows the word "Draft"
#### Screenshots

![image](https://cloud.githubusercontent.com/assets/17933351/15126654/ea42efb2-1600-11e6-89f9-09750404d50e.png)
#### Files

A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
#### To Reproduce

Go to Home > Blog > New Post. 
Create a post and publish it.
Got back to Home > Blog
#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Remember to use helpful labels and milestones. If you use the "help wanted" label, Code for America will [promote it widely](http://www.codeforamerica.org/geeks/civicissues).

**Comment by tracykm** [comment]
This is a UX design issue. The save draft button is where you would expect publish. The save draft and publish buttons should be switched and the save draft should be less prominently colored.
