### ISSUE TITLE
All Posts takes you Home

### ISSUE THREAD

**Issue by davidcarvel** [therebelrobot/brigadehub#267]
#### Description

The "All Posts" button on the Home page takes you to the top of the page.
#### Screenshots

![image](https://cloud.githubusercontent.com/assets/17933351/15126743/78053b02-1601-11e6-83f1-8be11a210c81.png)
#### Files

A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.
#### To Reproduce

Go to Home page. Scroll down. Select "All Posts"
#### Tasks

Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

Remember to use helpful labels and milestones. If you use the "help wanted" label, Code for America will [promote it widely](http://www.codeforamerica.org/geeks/civicissues).

**Comment by Juxtaposeidon** [comment]
fix #213
