### ISSUE TITLE
Directions for [heroku] deploy pipeline

### ISSUE THREAD

**Issue by patcon** [therebelrobot/brigadehub#35]
Heroku pipelines are in alpha but pretty slick. This is how I have it set up for one project in Toronto:

https://github.com/patcon/tocityhall-api#deployment

fwiw, this process depends on the deploy button process (ie. an `app.json` file):
https://devcenter.heroku.com/articles/heroku-button

**Comment by jnaulty** [comment]
@patcon 
Ever heard of git post hooks?
Here's a fun project we might find useful for deployment pipeline.
https://github.com/progrium/gitreceive

**Comment by afomi** [comment]
http://concourse.ci is also an interesting pipeline/build tool that is worth checking out

**Comment by howdoicomputer** [comment]
I've had good luck with Heroku's automated deployments off of git for one of my Ruby projects.
