### ISSUE TITLE
Add ability to remove sponsor as main sponsor

### ISSUE THREAD

**Issue by devdupont** [therebelrobot/brigadehub#496]
#### Description

There is currently no way to remove a sponsor as the main sponsor without removing and re-adding the entry

#### To Reproduce

Have at least one sponsor. Select as main. No ability to unmark.

**Comment by pltaylor** [comment]
This has been addressed in [this pull request](https://github.com/brigadehub/theme-admin-c4sf/pull/34).   Thank you for pointing this out, it is definitely something that needs to be addressed.

**Comment by pltaylor** [comment]
This will be fixed in the next release, and therefore I'm going to close this issue.  If there is any problem after that point please feel free to comment here and I will re-open it.
