### ISSUE TITLE
App crashes if Meetup url does not end with a slash (/)

### ISSUE THREAD

**Issue by devdupont** [therebelrobot/brigadehub#499]
#### Description

The entire application crashes if the "Meetup Group URL" field in manage brigade does not end with a slash. Ex: "Code-For-Orlando/" works; "Code-For-Orlando" crashes

#### To Reproduce

1. Set "Meetup Group URL" field to "Code-For-Orlando"

2. Save changes

3. Click "Sync Events with Meetup" button on the same page

4. Brigadehub crashes

#### Screenshots

Brigade admin with faulty meetup URL:

![meetupurl](https://cloud.githubusercontent.com/assets/2596237/24685409/550950b0-197b-11e7-9d30-69e00abd064f.png)

Initial loss of server connection:

![safari404](https://cloud.githubusercontent.com/assets/2596237/24685428/6c58f8e2-197b-11e7-81ba-ed667eaafa8f.png)

Full application crash:

![crash](https://cloud.githubusercontent.com/assets/2596237/24685435/78275a42-197b-11e7-9b1f-a4c8ad12f597.png)

**Comment by pltaylor** [comment]
There is a new PR for this issue @ [https://github.com/brigadehub/core/pull/31](https://github.com/brigadehub/core/pull/31)  The '/' is actually not needed (and causes a failure to get events at all).  What was happening was some of your events did not have a venue defined which was causing a null reference error when creating the events in BrigadeHub.  The PR adds a null check and everything imports in like it should!

**Comment by pltaylor** [comment]
This fix will be in the next release and therefore I'm going to close this.  If you run into any more problems with this feel free to comment here.
