### ISSUE TITLE
App crashes when saving events

### ISSUE THREAD

**Issue by devdupont** [therebelrobot/brigadehub#501]
#### Description

Our events now sync (thanks for that!), but the app crashes whenever the "Save Changes" button is clicked on the Manage Events page. Not sure if it's our events again, but the events do actually show up in the calendar when the site is rebooted. It also doesn't appear to be related to adding or removing location info on the page because the app will crash no matter what.

#### To Reproduce

1. Set the meetup group to "Code-For-Orlando" (not sure if specific to us again)

2. Click "Sync Events with Meetup" button

3. Page is successfully populated

4. Make changes or not. It doesn't seem to matter, but those changes are in fact saved

5. Click "Save Changes" button

6. App crashes

**Comment by pltaylor** [comment]
I've repo'ed this....and I'll work on it tomorrow.

**Comment by devdupont** [comment]
Playing around some more with this, editing the same details on an individual event's page do not cause the app to crash

**Comment by pltaylor** [comment]
I'm going to close this now that the PR has been merged.  This will be fixed in the next release.
