### ISSUE TITLE
App crashes when Active and Git Updates are checked

### ISSUE THREAD

**Issue by devdupont** [therebelrobot/brigadehub#506]
#### Description

When updating a project's details, the app will crash when both the "Active?" and "Git Updates" checkboxes are active. The app appears to crash before applying the changes to the database as they are not saved after rebooting the Heroku server.

#### To Reproduce

1. As admin, edit a project's details

2. Check both "Active?" and "Git Updates"

3. Click "Update Project"

4. App crashes

**Comment by pltaylor** [comment]
I'll try and repo this in the morning.

**Comment by pltaylor** [comment]
This appears to be another version of this [issue 503](https://github.com/brigadehub/brigadehub/issues/503).  I am going to mark this as a duplicate issue for now, but if you continue to see this after 503 has been fixed please comment here again and I'll reopen it and address it at that time.
